### PR TITLE
Swarthmore

### PR DESCRIPTION
**Pull request by jonorthwash**
I only added faculty affiliated with linguistics departments who teach / have taught computational linguistics.  I also only added specialisations for myself.

### CODE REVIEW

**Comment by nschneid** [comment]
Thanks. If I am choosing topics based on their websites I would say "phonology, historical linguistics, Southeast Asian languages" for Rikker and "phonology" for Jane.

@ftyers could you suggest topics for the IU faculty?

**Comment by jonorthwash** [comment]
You could probably add "formal language theory" for Jane.

**Comment by jonorthwash** [comment]
It occurs to me that Rutgers should be added too, with at least Adam Jardine and Simon Charlow.

**Comment by nschneid** [comment]
Yeah, there are a number of other institutions missing. I don't want to misrepresent anything so I'm going to wait for people from those institutions to submit.

**Comment by ftyers** [comment]
Oops, I missed this PR, in the other PR there are topics for the faculty.

**Pull request merged**
